# ============================================================
# Render Deployment Configuration for 6A Hotel
# ============================================================

services:
  - type: web
    name: 6a-hotel
    env: python
    region: frankfurt  # or 'oregon' if you prefer US region
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      npm install --prefix frontend/react_app
      npm run build --prefix frontend/react_app
      mkdir -p backend/frontend_build
      cp -r frontend/react_app/build/* backend/frontend_build/
      python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application
    autoDeploy: true

    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: .onrender.com,6ahotels.com,www.6ahotels.com
      - key: SECRET_KEY
        sync: false  # set manually in Render Dashboard
      - key: DATABASE_URL
        fromDatabase:
          name: 6a-hotel-db
          property: connectionString

databases:
  - name: 6a-hotel-db
    databaseName: hotel_db
    plan: free
